package com.netftplab

import android.Manifest
import android.content.Context
import android.net.ConnectivityManager
import android.net.Uri
import android.os.Bundle
import android.provider.OpenableColumns
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.lifecycle.lifecycleScope
import kotlinx.coroutines.*
import java.io.*
import java.net.*
import java.security.MessageDigest
import java.text.SimpleDateFormat
import java.util.*
import kotlin.math.min

data class Device(val ip:String,val host:String="Unknown",val services:List<Int> = emptyList(),val latencyMs:Long?=null)
data class LogLine(val time:String,val layer:String,val text:String)
data class SessionStats(val rttMs:Long=0,val connected:Boolean=false,val target:String="",val bytes:Long=0,val throughputBps:Long=0)
data class RemoteEntry(val name:String,val size:Long,val directory:Boolean)
data class TransferState(val active:Boolean=false,val direction:String="",val name:String="",val done:Long=0,val total:Long=-1,val speedBps:Long=0,val message:String="Idle",val sha256Local:String="",val sha256Remote:String="",val verified:Boolean?=null)

class MainActivity:ComponentActivity(){
 private val discovered=mutableStateListOf<Device>(); private val logs=mutableStateListOf<LogLine>(); private val remoteFiles=mutableStateListOf<RemoteEntry>(); private val serverFiles=mutableStateListOf<File>()
 private var scanning by mutableStateOf(false); private var connectedTarget by mutableStateOf(""); private var serverRunning by mutableStateOf(false); private var serverPort by mutableIntStateOf(2121); private var transfer by mutableStateOf(TransferState()); private var session by mutableStateOf(SessionStats()); private var showQr by mutableStateOf(false)
 private var ftp:FtpClient?=null; private lateinit var server:FtpServer; private lateinit var transferRoot:File; private lateinit var serverRoot:File
 private val uploadDocument=registerForActivityResult(ActivityResultContracts.OpenDocument()){u->if(u!=null)uploadUri(u)}
 private val shareDocument=registerForActivityResult(ActivityResultContracts.OpenDocument()){u->if(u!=null)importToServer(u)}
 override fun onCreate(b:Bundle?){super.onCreate(b);transferRoot=File(getExternalFilesDir(null),"NetFTPLabTransfers").apply{mkdirs()};serverRoot=File(getExternalFilesDir(null),"NetFTPShare").apply{mkdirs()};server=FtpServer(serverRoot,logger=::log);refreshServerFiles();if(android.os.Build.VERSION.SDK_INT>=33)requestPermissions(arrayOf(Manifest.permission.POST_NOTIFICATIONS),40);setContent{NetFtpApp()}}
 override fun onDestroy(){try{ftp?.close()}catch(_:Exception){};server.stop();super.onDestroy()}
 private fun log(layer:String,text:String){val t=SimpleDateFormat("HH:mm:ss.SSS",Locale.US).format(Date());runOnUiThread{logs.add(LogLine(t,layer,text));while(logs.size>800)logs.removeAt(0);if(layer=="DATA"&&text.startsWith("STOR "))refreshServerFiles()}}
 private fun localIpv4():String?{val cm=getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager;val lp=cm.getLinkProperties(cm.activeNetwork)?:return null;return lp.linkAddresses.firstOrNull{it.address is Inet4Address}?.address?.hostAddress}
 private fun localSubnet():String?=localIpv4()?.substringBeforeLast('.')
 private fun scanNetwork(){if(scanning)return;scanning=true;discovered.clear();log("DISCOVERY","Starting active LAN discovery");val subnet=localSubnet();if(subnet==null){log("ERROR","No IPv4 LAN interface found");scanning=false;return};log("DISCOVERY","Probing $subnet.0/24: FTP 21/2121, HTTP 80/443");lifecycleScope.launch(Dispatchers.IO){val found=Collections.synchronizedList(mutableListOf<Device>());coroutineScope{(1..254).map{n->async{val ip="$subnet.$n";val open=mutableListOf<Int>();var latency:Long?=null;listOf(21,2121,80,443).forEach{p->val t=System.currentTimeMillis();try{Socket().use{s->s.connect(InetSocketAddress(ip,p),220);if(latency==null)latency=System.currentTimeMillis()-t;open+=p}}catch(_:Exception){}};if(open.isNotEmpty())found+=Device(ip,services=open,latencyMs=latency)}}}.awaitAll()};withContext(Dispatchers.Main){discovered.addAll(found.sortedBy{it.ip.substringAfterLast('.').toIntOrNull()?:999});log("DISCOVERY","Scan complete: ${found.size} active service-bearing devices");scanning=false}}}
 private fun connect(d:Device){lifecycleScope.launch(Dispatchers.IO){try{ftp?.close();val port=when{2121 in d.services->2121;21 in d.services->21;else->return@launch};log("TCP","Opening FTP control connection ${d.ip}:$port");val c=FtpClient(d.ip,port,::log);c.connect();c.login("anonymous","anonymous@netftp.local");ftp=c;connectedTarget="${d.ip}:$port";session=SessionStats(connected=true,target=connectedTarget);log("TCP","FTP session established to $connectedTarget");refreshRemote()}catch(e:Exception){ftp=null;connectedTarget="";session=SessionStats();log("ERROR","Connection failed: ${e.message}")}}}
 private fun disconnect(){try{ftp?.quit()}catch(_:Exception){try{ftp?.close()}catch(_:Exception){}};ftp=null;connectedTarget="";session=SessionStats();remoteFiles.clear();transfer=TransferState(message="Disconnected");log("TCP","FTP client disconnected")}
 private fun refreshRemote(){val c=ftp?:return;lifecycleScope.launch(Dispatchers.IO){try{val parsed=parseListing(c.list());withContext(Dispatchers.Main){remoteFiles.clear();remoteFiles.addAll(parsed);session=session.copy(connected=true)}}catch(e:Exception){log("ERROR","LIST failed: ${e.message}");if(c===ftp){ftp=null;withContext(Dispatchers.Main){connectedTarget="";session=SessionStats()}}}}}
 private fun parseListing(text:String):List<RemoteEntry> =text.lineSequence().mapNotNull{line->val s=line.trim();if(s.isBlank())return@mapNotNull null;val p=s.split(Regex("\\s+"),limit=9);if(p.size>=9)RemoteEntry(p[8],p[4].toLongOrNull()?:0,p[0].startsWith("d"))else RemoteEntry(s,0,false)}.filterNot{it.name=="."||it.name==".."}.toList()
 private fun uploadUri(uri:Uri){val c=ftp;if(c==null||connectedTarget.isBlank()){transfer=TransferState(message="Not connected — select a device in Devices first");log("ERROR","Upload requested without an FTP client connection");return};val name=queryDisplayName(uri)?:"upload-${System.currentTimeMillis()}";lifecycleScope.launch(Dispatchers.IO){try{val size=contentLength(uri);val existing=c.remoteSize(name);var skip=if(existing>0&&size>existing)existing else 0L;val input=contentResolver.openInputStream(uri)?:throw IOException("Cannot open selected file");if(skip>0){var left=skip;while(left>0){val n=input.skip(left);if(n<=0)break;left-=n};skip-=left};val start=System.currentTimeMillis();transfer=TransferState(true,"UPLOAD",name,skip,size,0,if(skip>0)"Resuming" else "Starting");c.upload(name,input,size,skip){done,total->val ms=maxOf(1,System.currentTimeMillis()-start);transfer=transfer.copy(done=done,total=total,speedBps=done*1000/ms,message="Transferring")};input.close();verifyRemote(name,uri,size)}catch(e:Exception){transfer=transfer.copy(active=false,message="Upload failed: ${e.message}");log("ERROR","Upload failed: ${e.message}")}finally{refreshRemote()}}}
 private fun download(e:RemoteEntry){val c=ftp?:return;if(e.directory)return;lifecycleScope.launch(Dispatchers.IO){try{val outFile=File(transferRoot,e.name).canonicalFile;if(!outFile.path.startsWith(transferRoot.canonicalPath+File.separator))throw IOException("Unsafe filename");val total=c.remoteSize(e.name).takeIf{it>=0}?:e.size;val resume=if(outFile.exists())min(outFile.length(),total)else 0L;val start=System.currentTimeMillis();transfer=TransferState(true,"DOWNLOAD",e.name,resume,total,0,if(resume>0)"Resuming" else "Starting");RandomAccessFile(outFile,"rw").use{raf->raf.setLength(resume);raf.seek(resume);val out=object:OutputStream(){override fun write(b:Int)=raf.write(b);override fun write(b:ByteArray,o:Int,l:Int)=raf.write(b,o,l)};c.download(e.name,out,resume){done,t->val ms=maxOf(1,System.currentTimeMillis()-start);transfer=transfer.copy(done=done,total=t,speedBps=done*1000/ms,message="Transferring")};out.flush()};val lh=sha256(outFile);val rh=c.remoteSha256(e.name);transfer=transfer.copy(active=false,message="Complete",sha256Local=lh,sha256Remote=rh,verified=rh.takeIf{it.isNotBlank()}?.let{lh.equals(it,true)});session=session.copy(bytes=session.bytes+outFile.length());log("DATA","Saved ${outFile.absolutePath}; SHA-256 $lh")}catch(e:Exception){transfer=transfer.copy(active=false,message="Download failed: ${e.message}");log("ERROR","Download failed: ${e.message}")}}}
 private fun verifyRemote(name:String,uri:Uri,size:Long){val rh=ftp?.remoteSha256(name).orEmpty();val lh=contentSha256(uri);transfer=transfer.copy(active=false,message="Complete",sha256Local=lh,sha256Remote=rh,verified=rh.takeIf{it.isNotBlank()}?.let{lh.equals(it,true)});session=session.copy(bytes=session.bytes+size);log("DATA","Upload complete; local SHA-256=$lh remote SHA-256=${rh.ifBlank{"unsupported"}}")}
 private fun contentLength(u:Uri):Long=contentResolver.query(u,arrayOf(OpenableColumns.SIZE),null,null,null)?.use{c->if(c.moveToFirst()&&!c.isNull(0))c.getLong(0)else-1L}?:-1L
 private fun queryDisplayName(u:Uri):String?=contentResolver.query(u,arrayOf(OpenableColumns.DISPLAY_NAME),null,null,null)?.use{c->if(c.moveToFirst())c.getString(0)else null}
 private fun contentSha256(u:Uri):String=contentResolver.openInputStream(u)?.use{sha256(it)}?:""
 private fun sha256(f:File):String=FileInputStream(f).use{sha256(it)}
 private fun sha256(i:InputStream):String{val md=MessageDigest.getInstance("SHA-256");val b=ByteArray(64*1024);while(true){val n=i.read(b);if(n<0)break;md.update(b,0,n)};return md.digest().joinToString(""){"%02x".format(it)}}
 private fun refreshServerFiles(){if(!::serverRoot.isInitialized)return;serverFiles.clear();serverFiles.addAll(serverRoot.listFiles()?.sortedWith(compareBy<File>({!it.isDirectory},{it.name.lowercase(Locale.US)})).orEmpty())}
 private fun importToServer(u:Uri){val name=queryDisplayName(u)?.replace("/","_")?.replace("\\","_")?.ifBlank{"shared-${System.currentTimeMillis()}"}?:"shared-${System.currentTimeMillis()}";lifecycleScope.launch(Dispatchers.IO){try{val d=File(serverRoot,name).canonicalFile;if(!d.path.startsWith(serverRoot.canonicalPath+File.separator))throw IOException("Unsafe filename");contentResolver.openInputStream(u)?.use{s->FileOutputStream(d).use{o->s.copyTo(o,64*1024)}}?:throw IOException("Cannot open selected file");withContext(Dispatchers.Main){refreshServerFiles()};log("DATA","Phone share ready: ${d.name} (${d.length()} bytes)")}catch(e:Exception){log("ERROR","Preparing phone-to-laptop share failed: ${e.message}")}}}
 private fun saveServerFileToPhone(f:File){lifecycleScope.launch(Dispatchers.IO){try{val s=f.canonicalFile;if(!s.path.startsWith(serverRoot.canonicalPath+File.separator)||!s.isFile)throw IOException("Invalid shared file");val d=File(transferRoot,s.name).canonicalFile;if(!d.path.startsWith(transferRoot.canonicalPath+File.separator))throw IOException("Unsafe filename");s.inputStream().use{i->d.outputStream().use{o->i.copyTo(o,64*1024)}};transfer=TransferState(false,"LAPTOP → PHONE",s.name,d.length(),d.length(),0,"Saved on phone",sha256(d),"",null);log("DATA","Laptop-shared file copied to phone: ${d.absolutePath}")}catch(e:Exception){log("ERROR","Could not save shared file to phone: ${e.message}")}}}
 private fun deleteServerFile(f:File){lifecycleScope.launch(Dispatchers.IO){try{val c=f.canonicalFile;if(!c.path.startsWith(serverRoot.canonicalPath+File.separator))throw IOException("Unsafe path");if(c.isFile&&c.delete()){withContext(Dispatchers.Main){refreshServerFiles()};log("DATA","Server share deleted: ${c.name}")}else log("ERROR","Could not delete ${c.name}")}catch(e:Exception){log("ERROR","Delete failed: ${e.message}")}}}
 private fun toggleServer(){if(serverRunning){server.stop();serverRunning=false}else try{server.start();serverRunning=true;log("SERVER","Embedded FTP server active on ${localIpv4()?:"0.0.0.0"}:$serverPort")}catch(e:Exception){log("ERROR","Server start failed: ${e.message}")}}
 @OptIn(ExperimentalMaterial3Api::class) @Composable fun NetFtpApp(){var tab by remember{mutableIntStateOf(0)};MaterialTheme(colorScheme=darkColorScheme(primary=Color(0xFF60A5FA),secondary=Color(0xFF34D399),background=Color(0xFF080B10),surface=Color(0xFF11161E))){Scaffold(topBar={TopAppBar(title={Text("NetFTP Lab")},actions={IconButton(onClick=::scanNetwork){Icon(Icons.Default.Refresh,"Scan")}})},bottomBar={NavigationBar{listOf("Devices" to Icons.Default.Devices,"Transfers" to Icons.Default.SwapVert,"Console" to Icons.Default.Terminal,"Network Lab" to Icons.Default.Timeline,"Server" to Icons.Default.Settings).forEachIndexed{i,x->NavigationBarItem(selected=tab==i,onClick={tab=i},icon={Icon(x.second,null)},label={Text(x.first)})}}}){p->Box(Modifier.padding(p).fillMaxSize()){when(tab){0->DevicesTab();1->TransfersTab();2->ConsoleTab();3->NetworkLabTab();else->ServerTab()};if(showQr)QrDialog()}}}}
 @Composable private fun DevicesTab(){Column(Modifier.fillMaxSize().padding(16.dp)){Button(onClick=::scanNetwork,enabled=!scanning,modifier=Modifier.fillMaxWidth()){Text(if(scanning)"Scanning…" else "Scan LAN")};Spacer(Modifier.height(12.dp));if(discovered.isEmpty())Text("No devices discovered yet.");LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){items(discovered){d->Card(Modifier.fillMaxWidth().clickable{connect(d)}){Column(Modifier.padding(14.dp)){Text(d.ip,style=MaterialTheme.typography.titleMedium);Text("Services: ${d.services.joinToString()}${d.latencyMs?.let{" • ${it} ms"}?:""}")}}}}}}
 @Composable private fun TransfersTab(){Column(Modifier.fillMaxSize().padding(16.dp)){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text("FTP CLIENT CONNECTION",style=MaterialTheme.typography.labelLarge);Text(if(connectedTarget.isBlank())"NOT CONNECTED" else "CONNECTED • $connectedTarget",style=MaterialTheme.typography.titleMedium);if(connectedTarget.isBlank())Text("Select an FTP device from Devices to enable client transfers.")else{Text("Control channel: TCP ${connectedTarget.substringAfter(':')}");Text("Remote directory: ${remoteFiles.size} entries")};Spacer(Modifier.height(8.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp),modifier=Modifier.fillMaxWidth()){Button(onClick={uploadDocument.launch(arrayOf("*/*"))},enabled=connectedTarget.isNotBlank(),modifier=Modifier.weight(1f)){Text("Upload")};OutlinedButton(onClick=::refreshRemote,enabled=connectedTarget.isNotBlank(),modifier=Modifier.weight(1f)){Text("Refresh")};OutlinedButton(onClick=::disconnect,enabled=connectedTarget.isNotBlank(),modifier=Modifier.weight(1f)){Text("Disconnect")}}}};Spacer(Modifier.height(12.dp));if(transfer.active||transfer.message!="Idle"){Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text("${transfer.direction}: ${transfer.name}");if(transfer.total>0)LinearProgressIndicator(progress={transfer.done.toFloat().div(transfer.total).coerceIn(0f,1f)},modifier=Modifier.fillMaxWidth());Text("${transfer.message} • ${transfer.done}/${transfer.total} bytes • ${transfer.speedBps} B/s");if(transfer.sha256Local.isNotBlank())Text("SHA-256 local: ${transfer.sha256Local}");if(transfer.sha256Remote.isNotBlank())Text("SHA-256 remote: ${transfer.sha256Remote}");transfer.verified?.let{Text(if(it)"Integrity: VERIFIED" else "Integrity: MISMATCH")}}};Spacer(Modifier.height(12.dp))};Text("REMOTE FILES",style=MaterialTheme.typography.titleMedium);Text("Tap a remote file to download it to the phone.");Spacer(Modifier.height(6.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){items(remoteFiles){f->Card(Modifier.fillMaxWidth().clickable(enabled=connectedTarget.isNotBlank()){download(f)}){Row(Modifier.padding(14.dp),verticalAlignment=Alignment.CenterVertically){Icon(if(f.directory)Icons.Default.Folder else Icons.Default.InsertDriveFile,null);Spacer(Modifier.width(10.dp));Column{Text(f.name);Text(if(f.directory)"Directory" else "${f.size} bytes")}}}}}}}}
 @Composable private fun ConsoleTab(){Column(Modifier.fillMaxSize().padding(10.dp)){Row(verticalAlignment=Alignment.CenterVertically){Text("PROTOCOL CONSOLE",style=MaterialTheme.typography.titleMedium);Spacer(Modifier.weight(1f));TextButton(onClick={logs.clear()}){Text("Clear")}};LazyColumn(Modifier.fillMaxSize().background(Color(0xFF05070A)).padding(8.dp),verticalArrangement=Arrangement.spacedBy(2.dp)){items(logs){l->Text("${l.time} ${l.layer.padEnd(10)} ${l.text}",fontFamily=FontFamily.Monospace,style=MaterialTheme.typography.bodySmall)}}}}
 @Composable private fun NetworkLabTab(){var mode by remember{mutableStateOf("ALOHA")};var g by remember{mutableFloatStateOf(1f)};var cc by remember{mutableStateOf("RENO")};val s=when(mode){"SLOTTED"->NetworkLab.slottedThroughput(g.toDouble());"CSMA/CA"->NetworkLab.csmaCaThroughput(g.toDouble());else->NetworkLab.alohaThroughput(g.toDouble())};Column(Modifier.fillMaxSize().padding(16.dp).verticalScroll(rememberScrollState()),verticalArrangement=Arrangement.spacedBy(10.dp)){Text("NETWORK LAB",style=MaterialTheme.typography.headlineSmall);Text("MAC models are educational; ordinary Android apps cannot read every Wi-Fi collision.");Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("ALOHA","SLOTTED","CSMA/CA").forEach{m->OutlinedButton(onClick={mode=m}){Text(if(mode==m)"[$m]" else m)}}};Text("Offered load G: %.2f".format(g));Slider(value=g,onValueChange={g=it},valueRange=.05f..4f);Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text("Throughput S = %.4f".format(s));Text("Contention/collision index = %.1f%%".format((1-s).coerceIn(0.0,1.0)*100))}};Spacer(Modifier.height(10.dp));Text("TCP CONGESTION CONTROL",style=MaterialTheme.typography.titleMedium);Row(horizontalArrangement=Arrangement.spacedBy(6.dp)){listOf("RENO","CUBIC","BBR").forEach{c->OutlinedButton(onClick={cc=c}){Text(if(cc==c)"[$c]" else c)}}};val tr=NetworkLab.cwndTrace(cc);val maxY=tr.maxOf{it.y}.coerceAtLeast(1f);tr.takeLast(20).forEach{q->Row(verticalAlignment=Alignment.CenterVertically){Text("${q.x.toInt()}",Modifier.width(30.dp));LinearProgressIndicator(progress={(q.y/maxY).coerceIn(0f,1f)},modifier=Modifier.weight(1f));Text(" %.1f".format(q.y),Modifier.width(45.dp))}};Text("cwnd trace is modeled, not kernel TCP telemetry.")}}
 @Composable private fun ServerTab(){LaunchedEffect(Unit){refreshServerFiles()};Column(Modifier.fillMaxSize().padding(16.dp)){Text("Embedded FTP Server",style=MaterialTheme.typography.titleLarge);Spacer(Modifier.height(8.dp));Text(if(serverRunning)"RUNNING • ${localIpv4()?:"0.0.0.0"}:$serverPort" else "STOPPED");Spacer(Modifier.height(8.dp));Button(onClick=::toggleServer,modifier=Modifier.fillMaxWidth()){Text(if(serverRunning)"Stop Server" else "Start Server")};Spacer(Modifier.height(12.dp));Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp)){Text("Phone share folder: NetFTPShare",style=MaterialTheme.typography.titleMedium);Text("Add to Share is phone → laptop only. FTP client Upload is a separate operation in Transfers.");Spacer(Modifier.height(8.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp),modifier=Modifier.fillMaxWidth()){Button(onClick={shareDocument.launch(arrayOf("*/*"))},modifier=Modifier.weight(1f)){Text("Add to Share")};OutlinedButton(onClick=::refreshServerFiles,modifier=Modifier.weight(1f)){Text("Refresh")}}}};Spacer(Modifier.height(10.dp));Text("SHARED / INCOMING FILES",style=MaterialTheme.typography.titleMedium);Text("Laptop uploads and phone-shared files are stored in this FTP server folder.");Spacer(Modifier.height(6.dp));LazyColumn(verticalArrangement=Arrangement.spacedBy(6.dp),modifier=Modifier.weight(1f,fill=false)){items(serverFiles){f->Card(Modifier.fillMaxWidth()){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(f.name);Text("${f.length()} bytes • ${SimpleDateFormat("yyyy-MM-dd HH:mm:ss",Locale.US).format(Date(f.lastModified()))}")};if(f.isFile)IconButton(onClick={{ saveServerFileToPhone(f) }}){Icon(Icons.Default.Download,"Save to phone")};IconButton(onClick={{ deleteServerFile(f) }}){Icon(Icons.Default.Delete,"Delete")}}}}}};Spacer(Modifier.height(10.dp));Text("PHONE ↔ LAPTOP",style=MaterialTheme.typography.titleMedium);Text("Phone → laptop: Add to Share → Start Server → laptop opens ftp://${localIpv4()?:"PHONE_IP"}:$serverPort.\nLaptop → phone: upload to this server → the file appears above → tap the Download icon to copy it into the phone transfer area.");Spacer(Modifier.height(6.dp));OutlinedButton(onClick={showQr=true},modifier=Modifier.fillMaxWidth()){Text("Show FTP Endpoint")}}}
 @Composable private fun QrDialog(){AlertDialog(onDismissRequest={showQr=false},confirmButton={TextButton(onClick={showQr=false}){Text("Close")}},title={Text("FTP endpoint")},text={Text("ftp://${localIpv4()?:"PHONE_IP"}:$serverPort\n\nStart the server before connecting from the laptop.")})}
}
