from pathlib import Path

MAIN = Path("app/src/main/java/com/netftplab/MainActivity.kt")


def main() -> None:
    s = MAIN.read_text(encoding="utf-8")

    # This is intentionally a preservation/verification step. The complete
    # Transfer-tab UI is generated by apply_multi_file_transfer.py later in
    # the workflow. Rebuilding TransfersTab here used to erase newer download
    # controls and made the workflow dependent on obsolete source markers.
    start = s.find("    @Composable\n    private fun TransfersTab()")
    if start < 0:
        raise SystemExit("TransfersTab function not found")

    end = s.find("\n    private fun copyConsoleLog", start)
    if end < 0:
        # Some revisions place another private function immediately after the
        # tab. Do not require a particular following function name.
        end = s.find("\n    private fun ", start + 10)

    if end < 0:
        raise SystemExit("Unable to locate end of TransfersTab")

    tab = s[start:end]
    if "LazyColumn(" not in tab:
        # Do not rewrite the tab here. The later multi-file transfer step owns
        # the final scrollable Transfer-tab implementation.
        print("Transfer tab is not yet scrollable; deferred to multi-file transfer UI step")
    else:
        print("Transfer tab already uses LazyColumn; preserved existing UI")

    print("Transfer UI preservation check passed; server networking untouched")


if __name__ == "__main__":
    main()
