from pathlib import Path

path = Path("app/src/main/java/com/netftplab/MainActivity.kt")
text = path.read_text(encoding="utf-8")

# The transfer UI is now generated by apply_multi_file_transfer.py. This step
# must not rewrite it or depend on an obsolete row marker.
if 'Text(if (entry.directory) "Download Folder" else "Download File")' not in text:
    raise SystemExit("Individual file/folder download control is missing")
if 'Text("Download All (${selectableFiles.size})")' not in text:
    raise SystemExit("Download All control is missing")

print("Single-download controls verified; no source rewrite needed")
