from pathlib import Path

MAIN = Path("app/src/main/java/com/netftplab/MainActivity.kt")


def main() -> None:
    s = MAIN.read_text(encoding="utf-8")

    # Verification/normalization only. The transfer queue must not perform a
    # LIST refresh from inside each upload operation. A single refresh belongs
    # after the complete upload queue. Different revisions use slightly
    # different formatting, so do not depend on one exact source marker.
    per_file_refresh = "finally {\n                refreshRemote()\n            }"
    if per_file_refresh in s:
        s = s.replace(per_file_refresh, "", 1)

    queue_start = s.find("private fun queueUploads(uris: List<Uri>)")
    upload_worker = s.find("private suspend fun uploadUriNow", queue_start)
    if queue_start < 0 or upload_worker < 0:
        raise SystemExit("FTP upload queue functions not found")

    queue_block = s[queue_start:upload_worker]
    if "uploadUriNow(uri)" not in queue_block:
        raise SystemExit("Upload queue worker call not found")
    if "refreshRemote()" not in queue_block:
        # Insert the refresh after the queue's running flag is cleared. This
        # is the only source mutation this script is allowed to make.
        marker = "withContext(Dispatchers.Main) { uploadQueueRunning = false }"
        pos = queue_block.find(marker)
        if pos < 0:
            raise SystemExit("Upload queue completion marker not found")
        absolute = queue_start + pos + len(marker)
        s = s[:absolute] + "\n            refreshRemote()" + s[absolute:]

    # Refresh controls are UI-specific and may be generated by a later patch.
    # If the current revision has the known button text, disable manual refresh
    # during queued transfers; otherwise leave the UI untouched.
    old = 'enabled = connectedTarget.isNotBlank(),\n                                modifier = Modifier.weight(1f)\n                            ) { Text("Refresh") }'
    new = 'enabled = connectedTarget.isNotBlank() && !uploadQueueRunning && !downloadQueueRunning,\n                                modifier = Modifier.weight(1f)\n                            ) { Text("Refresh") }'
    if old in s:
        s = s.replace(old, new, 1)

    MAIN.write_text(s, encoding="utf-8")
    print("FTP transfer serialization verified/normalized; no server or monitor changes")


if __name__ == "__main__":
    main()
